import Mathlib.Data.Matrix.Basic
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.Tactic

namespace PrymLean

/-- The ideal generated by the `1 × 1` minors of a displayed `2 × 2`
presentation matrix.  This is deliberately a presentation-level definition,
not a general theory of Fitting ideals. -/
def presentationFittingOne₂
    {R : Type*} [CommRing R] (P : Matrix (Fin 2) (Fin 2) R) : Ideal R :=
  Ideal.span (Set.range fun ij : Fin 2 × Fin 2 => P ij.1 ij.2)

/-- The `1 × 1` minors of the universal-node presentation generate the ideal
of its four displayed parameters. -/
theorem universalNode_presentationFittingOne
    (R : Type*) [CommRing R] (ξ η p q : R) :
    presentationFittingOne₂ (!![η, q; p, ξ]) =
      Ideal.span ({ξ, η, p, q} : Set R) := by
  apply le_antisymm
  · apply Ideal.span_le.2
    rintro x ⟨⟨i, j⟩, rfl⟩
    fin_cases i <;> fin_cases j <;>
      apply Ideal.subset_span <;> simp
  · apply Ideal.span_le.2
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl | rfl
    · exact Ideal.subset_span ⟨(1, 1), by simp⟩
    · exact Ideal.subset_span ⟨(0, 0), by simp⟩
    · exact Ideal.subset_span ⟨(1, 0), by simp⟩
    · exact Ideal.subset_span ⟨(0, 1), by simp⟩

end PrymLean
